Introduce one whitelist file per device

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -8,20 +8,17 @@ LPURPLE='\033[1;35m'
 LNOCOLOR='\033[0m'
 REPO_DIR="$HOME/dotf2git"
 BACKUP_DIR="$REPO_DIR/my-dot-files"
-WHITELIST_FILE="$REPO_DIR/whitelist.txt"
+PUBWL="$REPO_DIR/src/pub"
+USER_WHITELIST="$REPO_DIR/src/pubwl"
 CONFIG_FILE="$HOME/.dotf2git"
 UPSTREAM_URL="git@github.com:PeachlifeAB/dotf2git.git"
 PWD=$(pwd)
 
 cd $REPO_DIR || { echo -e "${LRED}Failed to change directory to $REPO_DIR. Aborting.${LNOCOLOR}"; exit 1; }
 
-if [[ ! -f $WHITELIST_FILE ]]; then
-  echo -e "${LRED}Error: whitelist.txt file does not exist in $REPO_DIR. Aborting script.${LNOCOLOR}"
+if [[ ! -f $PUBWL ]]; then
+  echo -e "${LRED}Error: Public whitelist file does not exist. Aborting.${LNOCOLOR}"
   exit 1
-else
-  echo -e "${LYELLOW}Whitelist:${LNOCOLOR}"
-  cat "$WHITELIST_FILE"
-  echo ""
 fi
 
 # Check if Git is installed
@@ -47,9 +44,8 @@ get_user_remote_url() {
     REPO_URL="${REPO_URL:-$USER_REPO_URL}"
     git remote remove origin 2>/dev/null
     git remote remove upstream 2>/dev/null
-    git remote add origin $REPO_URL
-    git remote add upstream $UPSTREAM_URL
-
+    git remote add origin $REPO_URL 2>/dev/null
+    git remote add upstream $UPSTREAM_URL 2>/dev/null
     git push -u origin main || { echo -e "${LRED}Failed to push changes.${LNOCOLOR}"; git remote -v; rm $CONFIG_FILE; exit 1; }
   fi
 
@@ -88,20 +84,7 @@ echo -e "Upstream URL: ${LYELLOW}$UPSTREAM_REPO_URL${LNOCOLOR}"
 echo -e "Computer name: ${LYELLOW}$COMPUTER_NAME${LNOCOLOR}"
 echo "+----------------------------------------------------+"
 
-echo ""
-echo -e "${LYELLOW}Fetching changes from origin${LNOCOLOR}"
-
 git fetch origin || { echo -e "${LRED}Failed to fetch changes from origin.${LNOCOLOR}"; exit 1; }
-
-if ! git diff --quiet whitelist.txt; then
-  WHITELIST_STASH_ID=$(git stash push -m "Stashing changes to whitelist.txt" "$WHITELIST_FILE" | shasum | awk '{print $1}')
-  echo "Stashed changes with ID: $WHITELIST_STASH_ID"
-fi
-
-if ! git diff-index --quiet HEAD --; then
-  OTHER_STASH_ID=$(git stash push -m "Stashing other local changes" | shasum | awk '{print $1}')
-  echo "Stashed other local changes with ID: $OTHER_STASH_ID"
-fi
 
 if git show-ref --verify --quiet refs/heads/$COMPUTER_NAME; then
   echo -e "${LYELLOW}Switching to branch $COMPUTER_NAME${LNOCOLOR}"
@@ -110,18 +93,30 @@ else
   echo -e "${LYELLOW}Creating and switching to new branch $COMPUTER_NAME${LNOCOLOR}"
   git checkout -b "$COMPUTER_NAME" || { echo -e "${LRED}Failed to create and switch to branch $COMPUTER_NAME.${LNOCOLOR}"; exit 1; }
 fi
-
-echo -e "${LYELLOW}Updating $COMPUTER_NAME branch with latest features from origin/main.${LNOCOLOR}"
-git merge -X theirs -m "Merging in latest features from main" origin/main 2>/dev/null
-
-if [ -n "$WHITELIST_STASH_ID" ]; then
-  git stash apply $(git stash list | grep "$WHITELIST_STASH_ID" | cut -d: -f1) || { echo -e "${LRED}Failed to apply stashed changes to whitelist.txt.${LNOCOLOR}"; exit 1; }
+if [ ! -f "$COMPUTER_NAME.whitelist" ]; then
+    touch "$COMPUTER_NAME.whitelist"
+    git add . 2>/dev/null && git commit -m "$COMPUTER_NAME.whitelist added"
+    git push -u origin $COMPUTER_NAME
 fi
+if ! git diff --quiet "$COMPUTER_NAME.whitelist"; then
+  git add "$COMPUTER_NAME.whitelist"
+  git commit -m "$COMPUTER_NAME.whitelist updated"
+  git push origin "$COMPUTER_NAME" || { echo -e "${LRED}Failed to push local changes to the remote.${LNOCOLOR}"; exit 1; }
+fi
+if ! git diff-index --quiet HEAD --ignore-submodules --; then
+  git stash -u -q 2>/dev/null 
+  git restore --source=HEAD --staged --worktree . 2>/dev/null
+fi
+
+echo -e "${LYELLOW}Updating $COMPUTER_NAME branch with latest features from the users origin/main to device branch.${LNOCOLOR}"
+git merge -X theirs -m "Merging in latest features from main" origin/main 2>/dev/null
 
 rm -rf "$BACKUP_DIR"
 mkdir -p "$BACKUP_DIR" || { echo -e "${LRED}Failed to create backup directory.${LNOCOLOR}"; exit 1; }
 
-while IFS= read -r item; do
+sync_whitelist() {
+  local whitelist_file=$1
+  while IFS= read -r item; do
   item=$(echo "$item" | xargs)
   if [ -e "$HOME/$item" ]; then
     echo -e "${LGREEN}Syncing $item to $BACKUP_DIR/$item${LNOCOLOR}"
@@ -135,16 +130,14 @@ while IFS= read -r item; do
       cp -a "$HOME/$item" "$BACKUP_DIR/$item"
     fi
   fi
-done < "$WHITELIST_FILE"
+  done < "$whitelist_file"
+}
+sync_whitelist "$PUBWL"
+sync_whitelist "$COMPUTER_NAME.whitelist"
 
 git add "$BACKUP_DIR"
-GIT_STATUS=$(git status)
-echo ""
-echo -e "${LYELLOW}Git status:${LNOCOLOR}"
-echo "$GIT_STATUS"
-echo ""
 
-if echo "$GIT_STATUS" | grep -q "both modified"; then
+if echo "$(git status)" | grep -q "both modified"; then
   echo -e "${LRED}Conflict detected! Please resolve the conflict before committing and pushing changes.${LNOCOLOR}"
   echo -e "${LYELLOW}Use 'git mergetool' or edit the files manually to resolve the conflicts.${LNOCOLOR}"
   echo -e "${LYELLOW}After resolving the conflicts, use 'git add <file>' to mark them as resolved.${LNOCOLOR}"
@@ -153,7 +146,7 @@ if echo "$GIT_STATUS" | grep -q "both modified"; then
 fi
 
 if git diff --cached --exit-code > /dev/null; then
-  echo -e "${LYELLOW}No changes to commit.${LNOCOLOR}"
+  echo -e "${LYELLOW}No changes detected since last backup.${LNOCOLOR}"
 else
   echo -e "${LYELLOW}Files with changes${LNOCOLOR}"
   echo -e "${LYELLOW}-----------------------------------------${LNOCOLOR}"
@@ -167,20 +160,10 @@ else
   echo -e "${LGREEN}Your dot files have been updated and added to branch: ${LBLUE}$COMPUTER_NAME${LNOCOLOR}"
 fi
 
-if [ -n "$OTHER_STASH_ID" ]; then
-  read -p "Do you want to apply the stashed local changes (other than whitelist.txt)? (y/n): " APPLY_STASH
-  if [ "$APPLY_STASH" == "y" ] || [ "$APPLY_STASH" == "Y" ]; then
-    git stash apply $(git stash list | grep "$OTHER_STASH_ID" | cut -d: -f1) || { echo -e "${LRED}Failed to apply other stashed changes.${LNOCOLOR}"; exit 1; }
-    echo -e "${LYELLOW}Applied stashed local changes.${LNOCOLOR}"
-  else
-    echo -e "${LYELLOW}Skipped applying stashed local changes.${LNOCOLOR}"
-  fi
-fi
-
 cd "$PWD"
 echo -e ""
 echo -e "+-------------------- ${LPURPLE}Need to backup other files?${LNOCOLOR} --------------------+"
-echo -e "| 1. Add file to whitelist.txt                                        |"
+echo -e "| 1. Add files or folder, one per line to $COMPUTER_NAME.whitelist     |"
 echo -e "| 2. Run ~/dotf2git/backup to sync and commit changes                  |"
 echo -e "+---------------------------------------------------------------------+"
 echo -e "${LNOCOLOR}"
diff --git a/update b/update
--- a/update
+++ b/update
@@ -7,38 +7,33 @@ LNOCOLOR='\033[0m'
 REPO_DIR="$HOME/dotf2git"
 UPSTREAM_URL="git@github.com:PeachlifeAB/dotf2git.git"
 PWD=$(pwd)
-LOCAL_CHANGES=0
 
 echo -e "+-------------------- Debug Info --------------------+"
 echo -e "REPO_DIR: ${LYELLOW}$REPO_DIR${LNOCOLOR}"
 echo -e "+----------------------------------------------------+"
 
-cd $REPO_DIR || { echo -e "${LRED}Failed to change directory to $REPO_DIR. Aborting.${LNOCOLOR}"; exit 1; }
+cd "$REPO_DIR" || { echo -e "${LRED}Failed to change directory to $REPO_DIR. Aborting.${LNOCOLOR}"; exit 1; }
 CURRENT_BRANCH=$(git branch --show-current)
 
 echo -e "${LYELLOW}Fetching latest changes from upstream${LNOCOLOR}"
-git fetch --all || { echo -e "${LRED}Failed to fetch changes.${LNOCOLOR}"; exit 1; }
+git fetch --all --quiet || { echo -e "${LRED}Failed to fetch changes.${LNOCOLOR}"; exit 1; }
 
-if ! git diff-index --quiet HEAD --; then
-  echo -e "${LYELLOW}Stashing local changes before checking out main branch.${LNOCOLOR}"
-  LOCAL_CHANGES=1
-  git stash 2>/dev/null
+git checkout main --quiet || { echo -e "${LRED}Failed to switch to main branch.${LNOCOLOR}"; exit 1; }
+
+if ! git diff-index --quiet HEAD --ignore-submodules --; then
+  echo -e "${LYELLOW}Stashing local changes${LNOCOLOR}"
+  git stash -u -q 2>/dev/null || { echo -e "${LRED}Failed to stash local changes.${LNOCOLOR}"; exit 1; }
+  git reset --hard HEAD --quiet || { echo -e "${LRED}Failed to reset local changes.${LNOCOLOR}"; exit 1; }
 fi
 
-git checkout main || { echo -e "${LRED}Failed to switch to main branch.${LNOCOLOR}"; exit 1; }
+echo -e "${LYELLOW}Merging latest changes from origin/main into main${LNOCOLOR}"
+git merge -X theirs --quiet -m "Merging latest changes from origin/main into main" origin/main || { echo -e "${LRED}Failed to merge changes from origin/main.${LNOCOLOR}"; exit 1; }
 
-git merge -X theirs -m "Merging latest changes from origin/main into main" || { echo -e "${LRED}Failed to merge changes from origin/main.${LNOCOLOR}"; exit 1; }
+echo -e "${LYELLOW}Merging latest changes from upstream/main into main${LNOCOLOR}"
+git merge -X theirs --quiet -m "Merging latest changes from upstream/main" upstream/main || { echo -e "${LRED}Failed to merge changes from upstream.${LNOCOLOR}"; exit 1; }
 
-echo -e "${LYELLOW}Merging latest changes from upstream into main${LNOCOLOR}"
-git merge -X theirs -m "Meging in latest features from upstream" upstream/main || { echo -e "${LRED}Failed to merge changes from upstream.${LNOCOLOR}"; exit 1; }
-
-git push origin main || { echo -e "${LRED}Failed to push updates from upstream to origin main.${LNOCOLOR}"; exit 1; }
-
-git checkout "$CURRENT_BRANCH" || { echo -e "${LRED}Failed to switch back to branch: $CURRENT_BRANCH${LNOCOLOR}"; exit 1; }
-
-if [ "$LOCAL_CHANGES" -eq 1 ]; then
-  git stash pop
-fi
+echo -e "${LYELLOW}Pushing updates to origin main${LNOCOLOR}"
+git push origin main --quiet || { echo -e "${LRED}Failed to push updates from upstream to origin main.${LNOCOLOR}"; exit 1; }
 
 cd "$PWD"
 echo -e "${LGREEN}Update complete!${LNOCOLOR}"
