Run quiet

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -8,7 +8,7 @@ LPURPLE='\033[1;35m'
 LNOCOLOR='\033[0m'
 REPO_DIR="$HOME/dotf2git"
 BACKUP_DIR="$REPO_DIR/my-dot-files"
-PUBWL="$REPO_DIR/src/pub"
+PUBWL="$REPO_DIR/src/pubwl"
 USER_WHITELIST="$REPO_DIR/src/pubwl"
 CONFIG_FILE="$HOME/.dotf2git"
 UPSTREAM_URL="git@github.com:PeachlifeAB/dotf2git.git"
@@ -21,7 +21,6 @@ if [[ ! -f $PUBWL ]]; then
   exit 1
 fi
 
-# Check if Git is installed
 if ! command -v git &> /dev/null; then
   echo -e "${LRED}Error: Git is not installed. Please install Git and try again.${LNOCOLOR}"
   exit 1
@@ -46,13 +45,12 @@ get_user_remote_url() {
     git remote remove upstream 2>/dev/null
     git remote add origin $REPO_URL 2>/dev/null
     git remote add upstream $UPSTREAM_URL 2>/dev/null
-    git push -u origin main || { echo -e "${LRED}Failed to push changes.${LNOCOLOR}"; git remote -v; rm $CONFIG_FILE; exit 1; }
+    git push -u origin main --quiet || { echo -e "${LRED}Failed to push changes.${LNOCOLOR}"; git remote -v; rm $CONFIG_FILE; exit 1; }
   fi
 
   ORIGIN_REPO_URL="$(git remote get-url origin)"
   UPSTREAM_REPO_URL="$(git remote get-url upstream)"
   
-  # Precaution
   if [[ "$ORIGIN_REPO_URL" == *"github.com:PeachlifeAB/dotf2git.git" ]] && [[ "$UPSTREAM_REPO_URL" == *"github.com:PeachlifeAB/dotf2git.git" ]]; then
     echo -e "${LRED}Fatal error: Running backup script with $ORIGIN_REPO_URL as origin.${LNOCOLOR}"
     git remote remove upstream 2>/dev/null
@@ -69,10 +67,7 @@ else
     HOST=$(hostname)
 fi
 
-# Remove all non-alphanumeric characters except for spaces
 CLEANED_HOST=$(echo $HOST | sed 's/[^a-zA-Z0-9 ]//g')
-
-# Replace spaces with underscores
 COMPUTER_NAME=$(echo $CLEANED_HOST | sed 's/ /_/g')
 
 echo "+-------------------- Debug Info --------------------+"
@@ -84,32 +79,35 @@ echo -e "Upstream URL: ${LYELLOW}$UPSTREAM_REPO_URL${LNOCOLOR}"
 echo -e "Computer name: ${LYELLOW}$COMPUTER_NAME${LNOCOLOR}"
 echo "+----------------------------------------------------+"
 
-git fetch origin || { echo -e "${LRED}Failed to fetch changes from origin.${LNOCOLOR}"; exit 1; }
+git fetch origin --quiet || { echo -e "${LRED}Failed to fetch changes from origin.${LNOCOLOR}"; exit 1; }
 
 if git show-ref --verify --quiet refs/heads/$COMPUTER_NAME; then
   echo -e "${LYELLOW}Switching to branch $COMPUTER_NAME${LNOCOLOR}"
-  git checkout "$COMPUTER_NAME" || { echo -e "${LRED}Failed to switch to branch $COMPUTER_NAME.${LNOCOLOR}"; exit 1; }
+  git checkout "$COMPUTER_NAME" > /dev/null 2>&1 || { echo -e "${LRED}Failed to switch to branch $COMPUTER_NAME.${LNOCOLOR}"; exit 1; }
 else
   echo -e "${LYELLOW}Creating and switching to new branch $COMPUTER_NAME${LNOCOLOR}"
-  git checkout -b "$COMPUTER_NAME" || { echo -e "${LRED}Failed to create and switch to branch $COMPUTER_NAME.${LNOCOLOR}"; exit 1; }
+  git checkout -b "$COMPUTER_NAME" > /dev/null 2>&1 || { echo -e "${LRED}Failed to create and switch to branch $COMPUTER_NAME.${LNOCOLOR}"; exit 1; }
 fi
+
 if [ ! -f "$COMPUTER_NAME.whitelist" ]; then
     touch "$COMPUTER_NAME.whitelist"
-    git add . 2>/dev/null && git commit -m "$COMPUTER_NAME.whitelist added"
-    git push -u origin $COMPUTER_NAME
+    git add "$COMPUTER_NAME.whitelist" > /dev/null 2>&1 && git commit -m "$COMPUTER_NAME.whitelist added" --quiet
+    git push -u origin "$COMPUTER_NAME" --quiet
 fi
+
 if ! git diff --quiet "$COMPUTER_NAME.whitelist"; then
-  git add "$COMPUTER_NAME.whitelist"
-  git commit -m "$COMPUTER_NAME.whitelist updated"
-  git push origin "$COMPUTER_NAME" || { echo -e "${LRED}Failed to push local changes to the remote.${LNOCOLOR}"; exit 1; }
+  git add "$COMPUTER_NAME.whitelist" > /dev/null 2>&1
+  git commit -m "$COMPUTER_NAME.whitelist updated" --quiet
+  git push origin "$COMPUTER_NAME" --quiet || { echo -e "${LRED}Failed to push local changes to the remote.${LNOCOLOR}"; exit 1; }
 fi
+
 if ! git diff-index --quiet HEAD --ignore-submodules --; then
   git stash -u -q 2>/dev/null 
-  git restore --source=HEAD --staged --worktree . 2>/dev/null
+  git restore --source=HEAD --staged --worktree . > /dev/null 2>&1
 fi
 
 echo -e "${LYELLOW}Updating $COMPUTER_NAME branch with latest features from the users origin/main to device branch.${LNOCOLOR}"
-git merge -X theirs -m "Merging in latest features from main" origin/main 2>/dev/null
+git merge -X theirs -m "Merging in latest features from main" origin/main --quiet 2>/dev/null
 
 rm -rf "$BACKUP_DIR"
 mkdir -p "$BACKUP_DIR" || { echo -e "${LRED}Failed to create backup directory.${LNOCOLOR}"; exit 1; }
@@ -117,25 +115,24 @@ mkdir -p "$BACKUP_DIR" || { echo -e "${LRED}Failed to create backup directory.${
 sync_whitelist() {
   local whitelist_file=$1
   while IFS= read -r item; do
-  item=$(echo "$item" | xargs)
-  if [ -e "$HOME/$item" ]; then
-    echo -e "${LGREEN}Syncing $item to $BACKUP_DIR/$item${LNOCOLOR}"
-    mkdir -p "$BACKUP_DIR/$(dirname "$item")"
-    
-    if [ -d "$HOME/$item/.git" ]; then
-      echo -e "Unstaging nested git repository"
-      git rm --cached -r "$item"
-      rsync -av --exclude='.git' "$HOME/$item/" "$BACKUP_DIR/$item/"
-    else
-      cp -a "$HOME/$item" "$BACKUP_DIR/$item"
+    item=$(echo "$item" | xargs)
+    if [ -e "$HOME/$item" ]; then
+      echo -e "${LGREEN}Syncing $item to $BACKUP_DIR/$item${LNOCOLOR}"
+      mkdir -p "$BACKUP_DIR/$(dirname "$item")"
+      if [ -d "$HOME/$item/.git" ]; then
+        echo -e "Unstaging nested git repository"
+        git rm --cached -r "$item" > /dev/null 2>&1
+        rsync -av --exclude='.git' "$HOME/$item/" "$BACKUP_DIR/$item/"
+      else
+        cp -a "$HOME/$item" "$BACKUP_DIR/$item"
+      fi
     fi
-  fi
   done < "$whitelist_file"
 }
 sync_whitelist "$PUBWL"
 sync_whitelist "$COMPUTER_NAME.whitelist"
 
-git add "$BACKUP_DIR"
+git add "$BACKUP_DIR" > /dev/null 2>&1
 
 if echo "$(git status)" | grep -q "both modified"; then
   echo -e "${LRED}Conflict detected! Please resolve the conflict before committing and pushing changes.${LNOCOLOR}"
@@ -150,12 +147,12 @@ if git diff --cached --exit-code > /dev/null; then
 else
   echo -e "${LYELLOW}Files with changes${LNOCOLOR}"
   echo -e "${LYELLOW}-----------------------------------------${LNOCOLOR}"
-  echo -e "${LBLUE}$(git diff --cached --name-only)${LNOCOLOR}"
-  echo -e "${LYELLOW}-----------------------------------------${LNOCOLOR}"
+  echo -e "${LGREEN}$(git diff --cached --name-only)${LNOCOLOR}"
   echo ""
+  echo -e "${LYELLOW}-----------------------------------------${LNOCOLOR}"
   echo -e "${LYELLOW}Committing and pushing changes.${LNOCOLOR}"
-  git commit -m "Updating dot files for $COMPUTER_NAME" || { echo -e "${LRED}Failed to commit changes.${LNOCOLOR}"; exit 1; }
-  git push -u origin "$COMPUTER_NAME" || { echo -e "${LRED}Failed to push changes.${LNOCOLOR}"; exit 1; }
+  git commit -m "Updating dot files for $COMPUTER_NAME" --quiet || { echo -e "${LRED}Failed to commit changes.${LNOCOLOR}"; exit 1; }
+  git push -u origin "$COMPUTER_NAME" --quiet || { echo -e "${LRED}Failed to push changes.${LNOCOLOR}"; exit 1; }
   echo ""
   echo -e "${LGREEN}Your dot files have been updated and added to branch: ${LBLUE}$COMPUTER_NAME${LNOCOLOR}"
 fi
