Stash before running the update script

diff --git a/update b/update
--- a/update
+++ b/update
@@ -17,9 +17,11 @@ cd $REPO_DIR || { echo -e "${LRED}Failed to change directory to $REPO_DIR. Abort
 echo -e "${LGRAY}Fetching latest changes from upstream${LNOCOLOR}"
 git fetch upstream || { echo -e "${LRED}Failed to fetch changes from upstream.${LNOCOLOR}"; exit 1; }
 
+echo -e "${LYELLOW}Stashing any local changes before checking out $COMPUTER_NAME branch.${LNOCOLOR}"
+git stash 2>/dev/null
 echo -e "${LGRAY}Merging latest changes from upstream into main${LNOCOLOR}"
 git checkout main || { echo -e "${LRED}Failed to switch to main branch.${LNOCOLOR}"; exit 1; }
-git merge upstream/main || { echo -e "${LRED}Failed to merge changes from upstream.${LNOCOLOR}"; exit 1; }
+git merge -X theirs -m "Meging in latest features from upstream" upstream/main || { echo -e "${LRED}Failed to merge changes from upstream.${LNOCOLOR}"; exit 1; }
 git push origin main || { echo -e "${LRED}Failed to push updates from upstream to origin main.${LNOCOLOR}"; exit 1; }
 
 echo -e "${LGREEN}Update complete!${LNOCOLOR}"
