Fix diagnostics in update script

diff --git a/update b/update
--- a/update
+++ b/update
@@ -5,35 +5,57 @@ LYELLOW='\033[1;33m'
 LGREEN='\033[1;32m'
 LNOCOLOR='\033[0m'
 REPO_DIR="$HOME/dotf2git"
-UPSTREAM_URL="git@github.com:PeachlifeAB/dotf2git.git"
 PWD=$(pwd)
 
 echo -e "+-------------------- Debug Info --------------------+"
 echo -e "REPO_DIR: ${LYELLOW}$REPO_DIR${LNOCOLOR}"
 echo -e "+----------------------------------------------------+"
 
-cd "$REPO_DIR" || { echo -e "${LRED}Failed to change directory to $REPO_DIR. Aborting.${LNOCOLOR}"; exit 1; }
-CURRENT_BRANCH=$(git branch --show-current)
+cd "$REPO_DIR" || {
+  echo -e "${LRED}Failed to change directory to $REPO_DIR. Aborting.${LNOCOLOR}"
+  exit 1
+}
 
 echo -e "${LYELLOW}Fetching latest changes from upstream${LNOCOLOR}"
-git fetch --all --quiet || { echo -e "${LRED}Failed to fetch changes.${LNOCOLOR}"; exit 1; }
+git fetch --all --quiet || {
+  echo -e "${LRED}Failed to fetch changes.${LNOCOLOR}"
+  exit 1
+}
 
-git checkout main --quiet || { echo -e "${LRED}Failed to switch to main branch.${LNOCOLOR}"; exit 1; }
+git checkout main --quiet || {
+  echo -e "${LRED}Failed to switch to main branch.${LNOCOLOR}"
+  exit 1
+}
 
 if ! git diff-index --quiet HEAD --ignore-submodules --; then
   echo -e "${LYELLOW}Stashing local changes${LNOCOLOR}"
-  git stash -u -q 2>/dev/null || { echo -e "${LRED}Failed to stash local changes.${LNOCOLOR}"; exit 1; }
-  git reset --hard HEAD --quiet || { echo -e "${LRED}Failed to reset local changes.${LNOCOLOR}"; exit 1; }
+  git stash -u -q 2>/dev/null || {
+    echo -e "${LRED}Failed to stash local changes.${LNOCOLOR}"
+    exit 1
+  }
+  git reset --hard HEAD --quiet || {
+    echo -e "${LRED}Failed to reset local changes.${LNOCOLOR}"
+    exit 1
+  }
 fi
 
 echo -e "${LYELLOW}Merging latest changes from origin/main into main${LNOCOLOR}"
-git merge -X theirs --quiet -m "Merging latest changes from origin/main into main" origin/main || { echo -e "${LRED}Failed to merge changes from origin/main.${LNOCOLOR}"; exit 1; }
+git merge -X theirs --quiet -m "Merging latest changes from origin/main into main" origin/main || {
+  echo -e "${LRED}Failed to merge changes from origin/main.${LNOCOLOR}"
+  exit 1
+}
 
 echo -e "${LYELLOW}Merging latest changes from upstream/main into main${LNOCOLOR}"
-git merge -X theirs --quiet -m "Merging latest changes from upstream/main" upstream/main || { echo -e "${LRED}Failed to merge changes from upstream.${LNOCOLOR}"; exit 1; }
+git merge -X theirs --quiet -m "Merging latest changes from upstream/main" upstream/main || {
+  echo -e "${LRED}Failed to merge changes from upstream.${LNOCOLOR}"
+  exit 1
+}
 
 echo -e "${LYELLOW}Pushing updates to origin main${LNOCOLOR}"
-git push origin main --quiet || { echo -e "${LRED}Failed to push updates from upstream to origin main.${LNOCOLOR}"; exit 1; }
+git push origin main --quiet || {
+  echo -e "${LRED}Failed to push updates from upstream to origin main.${LNOCOLOR}"
+  exit 1
+}
 
-cd "$PWD"
+cd "$PWD" || exit
 echo -e "${LGREEN}Update complete!${LNOCOLOR}"
